// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx92zvd8me7VAy55DmSpz1Qvb8t9YsPu4',
    appId: '1:882088987402:web:2813f8c044df34aa6748f3',
    messagingSenderId: '882088987402',
    projectId: 'connectaa-9015d',
    authDomain: 'connectaa-9015d.firebaseapp.com',
    storageBucket: 'connectaa-9015d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1h639_OOAklfeh02oIIFW37VqbjB8J_s',
    appId: '1:882088987402:android:cb78c7bd023bf1366748f3',
    messagingSenderId: '882088987402',
    projectId: 'connectaa-9015d',
    storageBucket: 'connectaa-9015d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGVUHFbbfwagfOVUUNcGJyxbZmXHnSELY',
    appId: '1:882088987402:ios:44ffba93fd87e02f6748f3',
    messagingSenderId: '882088987402',
    projectId: 'connectaa-9015d',
    storageBucket: 'connectaa-9015d.appspot.com',
    iosBundleId: 'com.example.connectaa',
  );
}
